[Rule]

# ===== 本地 =====
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT

# ===== Apple 国内 =====
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN-KEYWORD,baidu,DIRECT
DOMAIN-KEYWORD,qq,DIRECT
DOMAIN-KEYWORD,taobao,DIRECT
DOMAIN-KEYWORD,alicdn,DIRECT
DOMAIN-KEYWORD,bilibili,DIRECT

# ===== 中国域名 =====
GEOIP,CN,DIRECT

# ===== 中国IP段 =====
IP-CIDR,1.0.1.0/24,DIRECT,no-resolve
IP-CIDR,1.0.2.0/23,DIRECT,no-resolve

# （这里不用手写全部IP，GEOIP已包含）

# ===== 国外流量 =====
FINAL,Proxy
